### ISSUE TITLE
About the pedal can't be used

### ISSUE THREAD

**Issue by LONG-9527** [larsmm/hoverboard-firmware-hack-FOC-bbcar#5]
Unable to calibrate the pedal, the tire rotates automatically after turning on. Continue to Didi, my English level is too low, I do not know if you can understand

**Comment by larsmm** [comment]
Use a translator. For example: https://www.deepl.com/de/translator

It is not possible that wheels are spinning after poweron. First it checks if both potis are on 0 position. If potis are non 0, it waits for them to get 0. Then it enables the motors and makes di-di sound.

On first poweron you have to calibrate the potis: So press and hold power-button for ~10 sec, until it beeps. Then move both potis and wait for another beep. It now should have saved min and max positions for both potis in eeprom.

**Comment by LONG-9527** [comment]
@larsmm How can I contact you?

**Comment by larsmm** [comment]
Make a video and show the problem.

**Comment by LONG-9527** [comment]
https://user-images.githubusercontent.com/127329914/227718505-fc88d86c-5ff1-4dcb-9fcd-d7adb53357da.mp4

**Comment by LONG-9527** [comment]
https://user-images.githubusercontent.com/127329914/227718550-b56a1db9-a5d7-4a0c-9bd1-e33033479083.mp4

**Comment by LONG-9527** [comment]
@larsmm

**Comment by LONG-9527** [comment]
@larsmm I don't know why, but my car is ready. This question has been bothering me for a long time

**Comment by LONG-9527** [comment]
@larsmmI have a good suggestion. I'll give you my BIN file to try, and you give me your bin file to try (the 36 lithium battery I use).

**Comment by LONG-9527** [comment]
At 2023-03-13 18:14:58, "larsmm" ***@***.***> wrote:

Use a translator. For example: https://www.deepl.com/de/translator

It is not possible that wheels are spinning after poweron. First it checks if both potis are on 0 position. If potis are non 0, it waits for them to get 0. Then it enables the motors and makes di-di sound.

On first poweron you have to calibrate the potis: So press and hold power-button for ~10 sec, until it beeps. Then move both potis and wait for another beep. It now should have saved min and max positions for both potis in eeprom.

**Comment by LONG-9527** [comment]
@larsmm
[firmware.zip](https://github.com/larsmm/hoverboard-firmware-hack-FOC-bbcar/files/11070585/firmware.zip)

**Comment by larsmm** [comment]
In version 1.100301.220327 of toolchain-gccarmnoneeabi package the adcs switched positions. In version 1.90301.200702 it is working like expected. There must be a serious problem in the code.

It is fixed in my newest commit. Please test again.

**Comment by LONG-9527** [comment]
@larsmm #define ADC_MARGIN still not working I've tweaked everything between 30 and 200 and my head is exploding

**Comment by LONG-9527** [comment]
Can you calibrate it automatically @larsmm

**Comment by LONG-9527** [comment]
你用什么社交软件 @larsmm

**Comment by LONG-9527** [comment]
What social media do you use @larsmm

**Comment by larsmm** [comment]
I did an update. Please try again. Please show debug output after calibrating. Use ADC_Margin 100 for now. Does it make a difference to end the calibration by short pressing power button?

**Comment by LONG-9527** [comment]
@larsmm It still doesn't work.

**Comment by LONG-9527** [comment]
[EFeru](https://github.com/EFeru)
/
[hoverboard-firmware-hack-FOC](https://github.com/EFeru/hoverboard-firmware-hack-FOC)
This three-speed one is fine

**Comment by larsmm** [comment]
Please post the serial debug output:
https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Debug-Serial

You will get lines like:
in1:345 in2:1337 cmdR:0 cmdL:0 BatADC:0 BatV:0 TempADC:0 Temp:0

in1 and in2 are the raw adc values of your pedals. Post values for not pressed and fully pressed for both pedals please. How much noise is there on min and max positions? If my firmware powers off too fast, use emanuels firmware.

**Comment by LONG-9527** [comment]
There's a brake problem in third gear
